adb push eglsubAndroid.so /system/lib/egl/eglsubAndroid.so
adb push libEGL_adreno200.so /system/lib/egl/libEGL_adreno200.so
adb push libGLESv1_CM_adreno200.so /system/lib/egl/libGLESv1_CM_adreno200.so
adb push libGLESv2_adreno200.so /system/lib/egl/libGLESv2_adreno200.so
adb push libq3dtools_adreno200.so /system/lib/egl/libq3dtools_adreno200.so
adb push libGLESv2S3D_adreno200.so /system/lib/egl/libGLESv2S3D_adreno200.so
adb push libplayback_adreno200.so /system/lib/egl/libplayback_adreno200.so
adb push libC2D2.so /system/lib/libC2D2.so
adb push libc2d2_z180.so /system/lib/libc2d2_z180.so
adb push libgsl.so /system/lib/libgsl.so
adb push libOpenVG.so /system/lib/libOpenVG.so
adb push libOpenCL.so /system/lib/libOpenCL.so
adb push libsc-a2xx.so /system/lib/libsc-a2xx.so
adb push a225p5_pm4.fw /system/etc/firmware/a225p5_pm4.fw
adb push a225_pfp.fw /system/etc/firmware/a225_pfp.fw
adb push a225_pm4.fw /system/etc/firmware/a225_pm4.fw
adb push leia_pfp_470.fw /system/etc/firmware/leia_pfp_470.fw
adb push leia_pm4_470.fw /system/etc/firmware/leia_pm4_470.fw
